#ifndef PG3401_V24_38_OPPGAVE3_MENU_H
#define PG3401_V24_38_OPPGAVE3_MENU_H

enum MENU_OPTIONS {
    MENU_OPTION_ADD_RESERVATION,
    MENU_OPTION_GET_RESERVATION,
    MENU_OPTION_SEARCH_RESERVATION,
    MENU_OPTION_DELETE_RESERVATION,
    MENU_OPTION_ADD_FOOD_AND_BEVERAGE,
    MENU_OPTION_PRINT_TABLE_ORDERS,
    MENU_OPTION_PRINT_ORDER_BY_GUEST,
    MENU_OPTION_PRINT_GUESTS_ORDERS,
    MENU_OPTION_EXIT
};

enum MENU_OPTIONS GetMenuOption();

#endif //PG3401_V24_38_OPPGAVE3_MENU_H
